// OWNER: Student A
// PURPOSE: Shared Election types used across the entire app.

export interface Ballot {
  voterId: string;
  ranking: Record<string, number>;  // e.g. {"pizza": 1, "tacos": 2, "chicken": 3}
}

export interface Election {
  id: string;                  // Globally unique, generated by API
  title: string;
  description: string;
  options: string[];           // The voting options
  ballots: Ballot[];           // Cast votes
  createdAt: number;           // Unix epoch ms
  opensAt: number;             // When voting opens
  closesAt: number;            // When voting closes (becomes immutable then)
  isDeleted: boolean;
  ownedByUs: boolean;          // True if our app created it (Req 2: Owned Elections)
}

// Derived state — compute from timestamps, don't store
export type ElectionStatus = 'upcoming' | 'open' | 'closed';

export function getElectionStatus(election: Election, now = Date.now()): ElectionStatus {
  if (now < election.opensAt) return 'upcoming';
  if (now >= election.closesAt) return 'closed';
  return 'open';
}

// For creating new elections — server generates id, createdAt
export interface NewElectionInput {
  title: string;
  description: string;
  options: string[];
  opensAt: number;
  closesAt: number;
}

// Results from the IRV algorithm — see lib/irv/
export interface IRVRound {
  roundNumber: number;
  tallies: Record<string, number>;
  eliminated: string | null;
  exhaustedBallots: number;
}

export interface IRVResult {
  winner: string | null;
  rounds: IRVRound[];
  totalBallots: number;
  isTie: boolean;
  tiedOptions: string[];
}
